# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
